name: build avalanche

on:
  push:
    paths:
#      - '**/*'  # only debug
      - avalanche/version.txt
      - avalanche/dockerfile.ci


jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        coin_folder: ['avalanche']

    env:  # set global vas
      DOCKER_REPO: denisitpro/coin-avalanche
      DOCKER_FILE: dockerfile.ci
      UBUNTU_IMAGE_VERSION: "24.04"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract version
        id: vars
        run: |
          cd ${{ matrix.coin_folder }}
          echo "VERSION=$(cat version.txt)"
          echo "VERSION=$(cat version.txt)" >> $GITHUB_ENV
          echo "TIMESTAMP=$(date -u +%Y%m%d%H%M%S)" >> $GITHUB_ENV


      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./${{ matrix.coin_folder }}
          file: ./${{ matrix.coin_folder }}/dockerfile.ci
          push: true
          tags: |
            ${{ env.DOCKER_REPO }}:${{ env.VERSION }}
            ${{ env.DOCKER_REPO }}:latest
          build-args: |
            TIMESTAMP=${{ env.TIMESTAMP }}
            VERSION=${{ env.VERSION }}
            UBUNTU_IMAGE_VERSION=${{ env.UBUNTU_IMAGE_VERSION }}
